baseurl = "https://teebobeet.github.io/1Mono2Voiles/"

title = "1 Mono 2 Voiles"
languageCode = "fr-fr"
metaDataFormat=  "yaml"
publishdir= "docs"
DefaultContentLanguage=  "fr"
uglyURLs=false

[author]
	name = "Teebo"

[params]
  sidebartitle = "1 Mono 2 Voiles"
  sidebartagline = "Fiches pour l'enseignement de la voile aux Glénans en tant que bénévole"
  author = "Teebo"
  categoriescss = "/css/categories.css"
	CopyrightHTML= "Copyright &#xA9; 2017 teebo.eu. All Rights Reserved."

[taxonomies]
  tag = "tags"
  categorie = "categories"
  poste = "postes"
  niveau = "niveaux"
	previsionnel = "previsionnels"
