baseurl = "http://teebo.eu/monovoile/"

title = "1 Mono 2 Voiles"
languageCode = "fr-fr"
metaDataFormat=  "yaml"
DefaultContentLanguage=  "fr"

[author]
	name = "Teebo"

[params]
  sidebartitle = "1 Mono 2 Voiles"
  sidebartagline = "Fiches pour l'enseignement de la voile aux Glénans en tant que bénévole"
  author = "Teebo"
  categoriescss = "/css/categories.css"
  
[taxonomies]
  tag = "tags"
  categorie = "categories"
  poste = "postes"
  niveau = "niveaux"

  